spring.application.name=final_project
spring.datasource.url=${DB_URL:jdbc:mariadb://project-db-campus.smhrd.com:3308/final_project}
spring.datasource.username=${DB_USERNAME:campus_24KDT_LI8_p3_bjh}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver