spring.application.name=final_project
server.port=8081
server.address=0.0.0.0
server.tomcat.basedir=./.tomcat
server.servlet.session.persistent=false

spring.datasource.url=jdbc:mariadb://project-db-campus.smhrd.com:3308/campus_24KDT_LI8_p3_bjh
spring.datasource.username=campus_24KDT_LI8_p3_bjh
spring.datasource.password=smhrd1
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.thymeleaf.cache=false
mybatis.configuration.map-underscore-to-camel-case=true